import { type Question } from '../../core/types';

const questions: Question[] = [
  // Easy
  { id: 1,  answer: "The Lion King",       clues: ["👑", "🦁", "🌅"],      difficulty: "easy",   aliases: ["lion king"],               hint: "Disney classic — 'Hakuna Matata'" },
  { id: 2,  answer: "Frozen",              clues: ["❄️", "👸", "⛄"],      difficulty: "easy",   aliases: [],                          hint: "Disney — 'Let It Go'" },
  { id: 3,  answer: "Finding Nemo",        clues: ["🐠", "🌊", "🔍"],      difficulty: "easy",   aliases: ["nemo"],                    hint: "Pixar — a clownfish searches the whole ocean" },
  { id: 4,  answer: "Toy Story",           clues: ["🤠", "🚀", "🧸"],      difficulty: "easy",   aliases: [],                          hint: "Pixar — toys come alive when humans leave" },
  { id: 5,  answer: "The Little Mermaid",  clues: ["🧜‍♀️", "🐚", "🌊"], difficulty: "easy",   aliases: ["little mermaid"],          hint: "Disney — she wants to be part of your world" },
  { id: 6,  answer: "Shrek",               clues: ["🧅", "🟢", "🐉"],      difficulty: "easy",   aliases: [],                          hint: "DreamWorks — a grumpy green ogre from a swamp" },
  { id: 7,  answer: "Cars",                clues: ["🏎️", "⚡", "🏁"],     difficulty: "easy",   aliases: [],                          hint: "Pixar — a racing car gets lost in a small town" },
  { id: 8,  answer: "Up",                  clues: ["🎈", "🏠", "👴"],      difficulty: "easy",   aliases: [],                          hint: "Pixar — a house floats away on thousands of balloons" },
  { id: 9,  answer: "Bambi",               clues: ["🦌", "🌲", "🌸"],      difficulty: "easy",   aliases: [],                          hint: "Disney — a young deer grows up in the forest" },
  { id: 10, answer: "Cinderella",          clues: ["👠", "🕛", "🏰"],      difficulty: "easy",   aliases: [],                          hint: "Disney — she must leave the ball by midnight" },
  { id: 11, answer: "Beauty and the Beast", clues: ["🌹", "🏰", "📚"],     difficulty: "easy",   aliases: ["beauty & the beast"],      hint: "Disney — a tale as old as time" },
  { id: 12, answer: "Monsters Inc",        clues: ["👹", "🚪", "👧"],      difficulty: "easy",   aliases: ["monsters inc.", "monsters incorporated"], hint: "Pixar — monsters power their city with children's screams" },
  { id: 13, answer: "Despicable Me",       clues: ["🟡", "😈", "👧"],      difficulty: "easy",   aliases: [],                          hint: "Illumination — a villain adopts three orphan girls" },
  { id: 14, answer: "The Jungle Book",     clues: ["🌿", "🐻", "👦"],      difficulty: "easy",   aliases: ["jungle book"],             hint: "Disney — a boy raised by wolves in India" },
  { id: 15, answer: "Peter Pan",           clues: ["✨", "🧚", "🏴‍☠️"],  difficulty: "easy",   aliases: [],                          hint: "Disney — the boy who never grows up" },
  { id: 16, answer: "Snow White",          clues: ["🍎", "👸", "🪞"],      difficulty: "easy",   aliases: ["snow white and the seven dwarfs"], hint: "Disney — 'Mirror, mirror on the wall'" },
  { id: 17, answer: "Tangled",             clues: ["💇‍♀️", "🏰", "🌟"], difficulty: "easy",   aliases: [],                          hint: "Disney — a princess with magical golden hair" },
  { id: 18, answer: "Ice Age",             clues: ["🧊", "🦣", "🌰"],      difficulty: "easy",   aliases: [],                          hint: "Blue Sky — prehistoric pals on a frozen adventure" },
  { id: 19, answer: "Madagascar",          clues: ["🦁", "🦓", "🏝️"],     difficulty: "easy",   aliases: [],                          hint: "DreamWorks — zoo animals escape to a wild island" },
  { id: 20, answer: "Happy Feet",          clues: ["🐧", "🎵", "🧊"],      difficulty: "easy",   aliases: [],                          hint: "A penguin who can't sing but can dance" },
  { id: 21, answer: "How to Train Your Dragon", clues: ["🐉", "🛡️", "🌊"], difficulty: "easy",  aliases: ["httyd"],                   hint: "DreamWorks — a Viking befriends a dragon" },
  { id: 22, answer: "Tarzan",              clues: ["🌿", "🦍", "🧔"],      difficulty: "easy",   aliases: [],                          hint: "Disney — a man raised by apes in the jungle" },

  // Medium
  { id: 23, answer: "Moana",               clues: ["🌊", "🌺", "⛵"],      difficulty: "medium", aliases: [],                          hint: "Disney — a Polynesian girl sails to save her island" },
  { id: 24, answer: "Coco",                clues: ["💀", "🎸", "🌸"],      difficulty: "medium", aliases: [],                          hint: "Pixar — set during Día de los Muertos in Mexico" },
  { id: 25, answer: "Zootopia",            clues: ["🦊", "🐰", "🚔"],      difficulty: "medium", aliases: ["zootropolis"],              hint: "Disney — a bunny becomes a police officer in a city of animals" },
  { id: 26, answer: "Inside Out",          clues: ["🧠", "😊", "😢"],      difficulty: "medium", aliases: [],                          hint: "Pixar — your emotions have a life of their own" },
  { id: 27, answer: "Ratatouille",         clues: ["🐀", "👨‍🍳", "🍽️"],  difficulty: "medium", aliases: [],                          hint: "Pixar — a rat dreams of cooking in Paris" },
  { id: 28, answer: "WALL-E",              clues: ["🤖", "🌍", "♻️"],      difficulty: "medium", aliases: ["walle", "wall e"],          hint: "Pixar — a lonely robot left behind on a trashed Earth" },
  { id: 29, answer: "Kung Fu Panda",       clues: ["🐼", "🥋", "🏮"],      difficulty: "medium", aliases: ["kungfu panda"],             hint: "DreamWorks — a clumsy panda becomes a kung fu master" },
  { id: 30, answer: "Aladdin",             clues: ["🧞‍♂️", "🪔", "✨"],  difficulty: "medium", aliases: [],                          hint: "Disney — three wishes from a magic lamp" },
  { id: 31, answer: "The Incredibles",     clues: ["🦸‍♂️", "👨‍👩‍👧‍👦", "🦹"], difficulty: "medium", aliases: ["incredibles"],       hint: "Pixar — a superhero family living in disguise" },
  { id: 32, answer: "Mulan",               clues: ["⚔️", "🐉", "🌸"],     difficulty: "medium", aliases: [],                          hint: "Disney — a woman disguises herself as a soldier" },
  { id: 33, answer: "Wreck-It Ralph",      clues: ["👊", "🕹️", "🍬"],     difficulty: "medium", aliases: ["wreck it ralph", "ralph"], hint: "Disney — a video game villain wants to be a hero" },
  { id: 34, answer: "The Iron Giant",      clues: ["🤖", "👦", "💥"],      difficulty: "medium", aliases: ["iron giant"],              hint: "A boy befriends a giant robot during the Cold War" },
  { id: 35, answer: "Big Hero 6",          clues: ["🤖", "🏥", "🎈"],      difficulty: "medium", aliases: [],                          hint: "Disney — a boy and his inflatable healthcare robot" },
  { id: 36, answer: "Turning Red",         clues: ["🔴", "🐼", "👧"],      difficulty: "medium", aliases: [],                          hint: "Pixar — a girl who transforms into a giant red panda" },
  { id: 37, answer: "Soul",                clues: ["🎹", "💫", "🌍"],      difficulty: "medium", aliases: [],                          hint: "Pixar — a jazz musician discovers the meaning of life" },
  { id: 38, answer: "Elemental",           clues: ["🔥", "💧", "💨"],      difficulty: "medium", aliases: [],                          hint: "Pixar — fire and water fall in love in Element City" },
  { id: 39, answer: "Megamind",            clues: ["🧠", "💙", "😈"],      difficulty: "medium", aliases: [],                          hint: "DreamWorks — a supervillain becomes the hero" },
  { id: 40, answer: "A Bug's Life",        clues: ["🐜", "🌿", "🎪"],      difficulty: "medium", aliases: ["bugs life", "a bugs life"], hint: "Pixar — an ant recruits circus bugs to fight grasshoppers" },
  { id: 41, answer: "Lilo and Stitch",     clues: ["👽", "🌺", "🏄"],      difficulty: "medium", aliases: ["lilo & stitch"],           hint: "Disney — a girl adopts an alien disguised as a dog" },
  { id: 42, answer: "Pocahontas",          clues: ["🌿", "🌊", "🍂"],      difficulty: "medium", aliases: [],                          hint: "Disney — 'Can you paint with all the colors of the wind?'" },
  { id: 43, answer: "Hercules",            clues: ["💪", "⚡", "🏛️"],     difficulty: "medium", aliases: [],                          hint: "Disney — a god becomes mortal, then earns his place on Olympus" },
  { id: 44, answer: "The Emperor's New Groove", clues: ["🦙", "👑", "😂"], difficulty: "medium", aliases: ["emperors new groove"],     hint: "Disney — an emperor gets turned into a llama" },
  { id: 45, answer: "Treasure Planet",     clues: ["🏴‍☠️", "🚀", "🗺️"], difficulty: "medium", aliases: [],                          hint: "Disney — Treasure Island, but in space" },
  { id: 46, answer: "Lightyear",           clues: ["🚀", "👨‍🚀", "🤖"],  difficulty: "medium", aliases: [],                          hint: "Pixar — the origin story of the space ranger Toy Story was based on" },
  { id: 47, answer: "Puss in Boots",       clues: ["🐱", "👢", "⚔️"],     difficulty: "medium", aliases: [],                          hint: "DreamWorks — a swashbuckling cat on his last life" },
  { id: 48, answer: "Onward",              clues: ["🧙", "🚐", "💜"],      difficulty: "medium", aliases: [],                          hint: "Pixar — two elf brothers try to bring back their dad for one day" },
  { id: 49, answer: "Brother Bear",        clues: ["🐻", "🌲", "🌌"],      difficulty: "medium", aliases: [],                          hint: "Disney — a man is transformed into a bear by the spirits" },
  { id: 50, answer: "The Good Dinosaur",   clues: ["🦕", "👦", "🏔️"],     difficulty: "medium", aliases: ["good dinosaur"],           hint: "Pixar — what if the asteroid never hit Earth?" },
  { id: 51, answer: "Monsters University", clues: ["👹", "🎓", "📚"],      difficulty: "medium", aliases: [],                          hint: "Pixar — a prequel about Mike and Sulley in college" },
  { id: 52, answer: "Cloudy With a Chance of Meatballs", clues: ["🌧️", "🍔", "🔬"], difficulty: "medium", aliases: ["cloudy with a chance of meatballs"], hint: "Sony — a machine makes food fall from the sky" },
  { id: 53, answer: "Strange World",       clues: ["🌿", "🗺️", "🔮"],     difficulty: "medium", aliases: [],                          hint: "Disney — a family explores a mysterious underground ecosystem" },

  // Hard
  { id: 54, answer: "Spirited Away",       clues: ["🛁", "👧", "🐉"],      difficulty: "hard",   aliases: [],                          hint: "Studio Ghibli — a girl trapped in a spirit bathhouse" },
  { id: 55, answer: "Encanto",             clues: ["🏡", "🎁", "🌺"],      difficulty: "hard",   aliases: [],                          hint: "Disney — a magical Colombian family, each with a gift" },
  { id: 56, answer: "Luca",                clues: ["🌊", "🏍️", "🇮🇹"],  difficulty: "hard",   aliases: [],                          hint: "Pixar — sea monsters discover an Italian coastal village" },
  { id: 57, answer: "Brave",               clues: ["🏹", "🐻", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"], difficulty: "hard",  aliases: [],                          hint: "Pixar — a Scottish princess accidentally turns her mum into a bear" },
  { id: 58, answer: "Coraline",            clues: ["🪡", "👁️", "🖤"],     difficulty: "hard",   aliases: [],                          hint: "Stop-motion — a girl finds a creepy parallel world behind a secret door" },
  { id: 59, answer: "The Princess and the Frog", clues: ["🐸", "👸", "🎺"], difficulty: "hard", aliases: ["princess and the frog"],    hint: "Disney — set in jazz-era New Orleans" },
  { id: 60, answer: "Bolt",                clues: ["⚡", "🐕", "🎬"],      difficulty: "hard",   aliases: [],                          hint: "Disney — a dog who thinks his TV superpowers are real" },
  { id: 61, answer: "Atlantis",            clues: ["🌊", "🗺️", "💎"],     difficulty: "hard",   aliases: ["atlantis the lost empire"], hint: "Disney — explorers search for a lost underwater city" },
  { id: 62, answer: "The Secret of NIMH",  clues: ["🐭", "💎", "🔬"],      difficulty: "hard",   aliases: ["secret of nimh"],          hint: "A mother mouse seeks help from super-intelligent rats" },
  { id: 63, answer: "The Prince of Egypt", clues: ["🏜️", "🌊", "👑"],     difficulty: "hard",   aliases: ["prince of egypt"],         hint: "DreamWorks — the story of Moses" },
  { id: 64, answer: "Fantastic Mr. Fox",   clues: ["🦊", "🐔", "🕳️"],     difficulty: "hard",   aliases: ["fantastic mr fox"],        hint: "Wes Anderson — a fox outwits three mean farmers" },
  { id: 65, answer: "Isle of Dogs",        clues: ["🐕", "🏝️", "🇯🇵"],  difficulty: "hard",   aliases: [],                          hint: "Wes Anderson — dogs are exiled to a trash island in Japan" },
  { id: 66, answer: "Kubo and the Two Strings", clues: ["🎸", "📜", "🗡️"], difficulty: "hard",  aliases: ["kubo"],                    hint: "Laika — a boy uses a magical shamisen to fight spirits" },
  { id: 67, answer: "Song of the Sea",     clues: ["🌊", "🎵", "🦭"],      difficulty: "hard",   aliases: [],                          hint: "Irish animation — a selkie child must save fairy folk" },
  { id: 68, answer: "Wolfwalkers",         clues: ["🐺", "🌙", "🌲"],      difficulty: "hard",   aliases: [],                          hint: "Cartoon Saloon — a girl discovers she becomes a wolf while sleeping" },
  { id: 69, answer: "The Red Turtle",      clues: ["🐢", "🔴", "🏝️"],     difficulty: "hard",   aliases: ["red turtle"],              hint: "Studio Ghibli — a castaway on a deserted island, told without dialogue" },
  { id: 70, answer: "My Neighbor Totoro",  clues: ["🌳", "☔", "😊"],       difficulty: "hard",   aliases: ["totoro"],                  hint: "Studio Ghibli — two sisters discover a friendly forest spirit" },
  { id: 71, answer: "Howl's Moving Castle", clues: ["🏰", "🔥", "✨"],     difficulty: "hard",   aliases: ["howls moving castle"],     hint: "Studio Ghibli — a girl cursed to be old finds a wizard's walking castle" },
  { id: 72, answer: "Princess Mononoke",   clues: ["🐺", "🌲", "⚔️"],     difficulty: "hard",   aliases: [],                          hint: "Studio Ghibli — a prince is caught between humans and forest gods" },
  { id: 73, answer: "Ponyo",               clues: ["🐟", "🌊", "👧"],      difficulty: "hard",   aliases: [],                          hint: "Studio Ghibli — a goldfish princess wants to become human" },
  { id: 74, answer: "Paprika",             clues: ["🌀", "💭", "🎪"],      difficulty: "hard",   aliases: [],                          hint: "Satoshi Kon — a device that lets therapists enter dreams is stolen" },
  { id: 75, answer: "The Breadwinner",     clues: ["📖", "✂️", "🌍"],      difficulty: "hard",   aliases: ["breadwinner"],             hint: "A girl in Taliban-era Afghanistan disguises herself as a boy" },
];

export default questions;
