import { type Question } from '../../core/types';

const questions: Question[] = [
  // Easy
  { id: 1,  answer: "Dog",         clues: ["🦴", "🎾", "🐾"],    difficulty: "easy",   aliases: ["puppy"],                   hint: "Domesticated for over 15,000 years" },
  { id: 2,  answer: "Cat",         clues: ["🐟", "🌙", "🧶"],    difficulty: "easy",   aliases: ["kitten"],                  hint: "Spends up to 16 hours a day sleeping" },
  { id: 3,  answer: "Elephant",    clues: ["👃", "💧", "🌍"],    difficulty: "easy",   aliases: [],                          hint: "Largest land animal on Earth" },
  { id: 4,  answer: "Lion",        clues: ["👑", "🌾", "🐾"],    difficulty: "easy",   aliases: [],                          hint: "Only big cat that lives in groups (prides)" },
  { id: 5,  answer: "Rabbit",      clues: ["🥕", "👂", "🌿"],    difficulty: "easy",   aliases: ["bunny", "hare"],           hint: "Teeth never stop growing" },
  { id: 6,  answer: "Penguin",     clues: ["🧊", "🐟", "🤵"],    difficulty: "easy",   aliases: [],                          hint: "Bird that cannot fly but can swim at 25 mph" },
  { id: 7,  answer: "Duck",        clues: ["🌊", "🍞", "🟡"],    difficulty: "easy",   aliases: ["duckling"],                hint: "Waterproof feathers thanks to a preen gland" },
  { id: 8,  answer: "Giraffe",     clues: ["🌍", "🍃", "🔝"],    difficulty: "easy",   aliases: [],                          hint: "Tallest living terrestrial animal" },
  { id: 9,  answer: "Horse",       clues: ["🏇", "🌾", "👟"],    difficulty: "easy",   aliases: ["pony"],                    hint: "Can sleep both standing up and lying down" },
  { id: 10, answer: "Pig",         clues: ["🐽", "🍎", "🌾"],    difficulty: "easy",   aliases: ["piglet"],                  hint: "Considered one of the smartest domesticated animals" },
  { id: 11, answer: "Cow",         clues: ["🥛", "🌾", "🔔"],    difficulty: "easy",   aliases: ["cattle"],                  hint: "Has almost 360-degree panoramic vision" },
  { id: 12, answer: "Chicken",     clues: ["🥚", "🌅", "🌾"],    difficulty: "easy",   aliases: ["hen", "rooster"],          hint: "Most common domesticated bird on Earth" },
  { id: 13, answer: "Fish",        clues: ["🌊", "🫧", "🪱"],    difficulty: "easy",   aliases: [],                          hint: "Some species can recognize human faces" },
  { id: 14, answer: "Snake",       clues: ["🌿", "☀️", "👅"],    difficulty: "easy",   aliases: ["serpent"],                  hint: "Smells with its tongue" },
  { id: 15, answer: "Bee",         clues: ["🍯", "🌸", "💛"],    difficulty: "easy",   aliases: ["honeybee"],                hint: "Can communicate through dance" },
  { id: 16, answer: "Butterfly",   clues: ["🌸", "🎨", "🌿"],    difficulty: "easy",   aliases: [],                          hint: "Tastes with its feet" },
  { id: 17, answer: "Mouse",       clues: ["🧀", "🏠", "🐾"],    difficulty: "easy",   aliases: ["mice"],                    hint: "Whiskers help it sense changes in temperature" },
  { id: 18, answer: "Shark",       clues: ["🌊", "🦷", "🔺"],    difficulty: "easy",   aliases: [],                          hint: "Has been around longer than trees" },
  { id: 19, answer: "Whale",       clues: ["🌊", "💨", "🎵"],    difficulty: "easy",   aliases: [],                          hint: "Largest animal ever known to have existed" },
  { id: 20, answer: "Deer",        clues: ["🌲", "🍂", "🌿"],    difficulty: "easy",   aliases: ["stag", "doe"],             hint: "Males shed and regrow antlers every year" },
  { id: 21, answer: "Fox",         clues: ["🌙", "🐾", "🟠"],    difficulty: "easy",   aliases: [],                          hint: "Uses Earth's magnetic field to hunt" },
  { id: 22, answer: "Hedgehog",    clues: ["🌙", "🍎", "🌿"],    difficulty: "easy",   aliases: [],                          hint: "Has about 5,000 to 7,000 quills" },

  // Medium
  { id: 23, answer: "Zebra",       clues: ["🌍", "🖤", "🤍"],    difficulty: "medium", aliases: [],                          hint: "Every individual has a unique stripe pattern" },
  { id: 24, answer: "Dolphin",     clues: ["🌊", "😊", "🐟"],    difficulty: "medium", aliases: [],                          hint: "Sleeps with one eye open" },
  { id: 25, answer: "Bear",        clues: ["🍯", "🌲", "😴"],    difficulty: "medium", aliases: ["grizzly", "grizzly bear"], hint: "Heartbeat drops to 8 beats per minute during hibernation" },
  { id: 26, answer: "Owl",         clues: ["🌙", "👀", "📚"],    difficulty: "medium", aliases: [],                          hint: "Cannot move its eyeballs — rotates its head instead" },
  { id: 27, answer: "Frog",        clues: ["🌧️", "🌿", "💚"],   difficulty: "medium", aliases: ["toad"],                    hint: "Drinks water through its skin, not its mouth" },
  { id: 28, answer: "Parrot",      clues: ["🌴", "🎨", "🗣️"],   difficulty: "medium", aliases: [],                          hint: "Can live for over 80 years" },
  { id: 29, answer: "Monkey",      clues: ["🌿", "🍌", "😄"],    difficulty: "medium", aliases: [],                          hint: "Has fingerprints almost identical to humans" },
  { id: 30, answer: "Koala",       clues: ["🌿", "😴", "🇦🇺"], difficulty: "medium", aliases: ["koala bear"],              hint: "Eats only eucalyptus leaves, which are toxic to most animals" },
  { id: 31, answer: "Flamingo",    clues: ["🩷", "🦵", "🌅"],    difficulty: "medium", aliases: [],                          hint: "Born white — pink color comes from its diet" },
  { id: 32, answer: "Gorilla",     clues: ["🌿", "💪", "🖤"],    difficulty: "medium", aliases: [],                          hint: "Shares about 98% of its DNA with humans" },
  { id: 33, answer: "Cheetah",     clues: ["🏃", "🌍", "🟡"],    difficulty: "medium", aliases: [],                          hint: "Fastest land animal — up to 70 mph" },
  { id: 34, answer: "Wolf",        clues: ["🌙", "🐾", "🌲"],    difficulty: "medium", aliases: [],                          hint: "Can hear sounds up to 6 miles away in the forest" },
  { id: 35, answer: "Bat",         clues: ["🌙", "🔊", "🦇"],    difficulty: "medium", aliases: [],                          hint: "Only mammal capable of true sustained flight" },
  { id: 36, answer: "Crocodile",   clues: ["🌊", "🦷", "🌿"],    difficulty: "medium", aliases: ["croc", "alligator"],       hint: "Has the strongest bite ever measured in a living animal" },
  { id: 37, answer: "Eagle",       clues: ["🏔️", "👁️", "🦅"],  difficulty: "medium", aliases: [],                          hint: "Can spot a rabbit from over 2 miles away" },
  { id: 38, answer: "Jellyfish",   clues: ["🌊", "💜", "⚡"],    difficulty: "medium", aliases: ["jelly fish"],              hint: "Has no brain, heart, or blood" },
  { id: 39, answer: "Panda",       clues: ["🖤", "🤍", "🎋"],    difficulty: "medium", aliases: ["giant panda"],             hint: "Spends 12 hours a day eating bamboo" },
  { id: 40, answer: "Kangaroo",    clues: ["🇦🇺", "🥊", "👜"], difficulty: "medium", aliases: [],                          hint: "Cannot walk backwards" },
  { id: 41, answer: "Raccoon",     clues: ["🌙", "🎭", "🗑️"],   difficulty: "medium", aliases: [],                          hint: "Washes its food before eating" },
  { id: 42, answer: "Otter",       clues: ["🌊", "🦦", "🤝"],    difficulty: "medium", aliases: ["sea otter"],               hint: "Holds hands while sleeping so they don't drift apart" },
  { id: 43, answer: "Swan",        clues: ["🌊", "🤍", "👑"],    difficulty: "medium", aliases: [],                          hint: "Mates for life — a symbol of love" },
  { id: 44, answer: "Lobster",     clues: ["🌊", "🔴", "🦞"],    difficulty: "medium", aliases: [],                          hint: "Can live to be over 100 years old" },
  { id: 45, answer: "Crab",        clues: ["🌊", "🏖️", "✌️"],   difficulty: "medium", aliases: [],                          hint: "Walks sideways because of the way its legs bend" },
  { id: 46, answer: "Starfish",    clues: ["🌊", "⭐", "🏖️"],    difficulty: "medium", aliases: ["sea star"],                hint: "Can regrow a lost arm" },
  { id: 47, answer: "Squirrel",    clues: ["🌰", "🌳", "🐾"],    difficulty: "medium", aliases: [],                          hint: "Forgets where it buries about half its nuts" },
  { id: 48, answer: "Hamster",     clues: ["🏠", "🌀", "🌻"],    difficulty: "medium", aliases: [],                          hint: "Can store food in its cheeks up to 20% of its body weight" },
  { id: 49, answer: "Tiger",       clues: ["🟠", "⬛", "🌿"],    difficulty: "medium", aliases: [],                          hint: "Has striped skin, not just striped fur" },
  { id: 50, answer: "Hippo",       clues: ["🌊", "💧", "🌍"],    difficulty: "medium", aliases: ["hippopotamus"],            hint: "Secretes a natural sunscreen that looks like blood" },
  { id: 51, answer: "Camel",       clues: ["🏜️", "💧", "🐪"],   difficulty: "medium", aliases: [],                          hint: "Can drink 40 gallons of water in one sitting" },
  { id: 52, answer: "Moose",       clues: ["🌲", "❄️", "🍁"],    difficulty: "medium", aliases: ["elk"],                     hint: "Largest member of the deer family" },
  { id: 53, answer: "Seal",        clues: ["🌊", "❄️", "🐟"],    difficulty: "medium", aliases: ["sea lion"],                hint: "Can hold its breath for up to 2 hours" },

  // Hard
  { id: 54, answer: "Octopus",     clues: ["🌊", "💜", "8️⃣"],   difficulty: "hard",   aliases: [],                          hint: "Has three hearts and blue blood" },
  { id: 55, answer: "Seahorse",    clues: ["🌊", "🐴", "🤰"],    difficulty: "hard",   aliases: ["sea horse"],               hint: "The male carries and gives birth to the young" },
  { id: 56, answer: "Peacock",     clues: ["💚", "💙", "👁️"],   difficulty: "hard",   aliases: [],                          hint: "Its tail is called a train, not a tail" },
  { id: 57, answer: "Chameleon",   clues: ["🎨", "🌿", "👀"],    difficulty: "hard",   aliases: [],                          hint: "Each eye can move independently" },
  { id: 58, answer: "Turtle",      clues: ["🌊", "🏠", "🐌"],    difficulty: "hard",   aliases: ["tortoise"],                hint: "Some species can live over 200 years" },
  { id: 59, answer: "Sloth",       clues: ["😴", "🙃", "🌳"],    difficulty: "hard",   aliases: [],                          hint: "Takes two weeks to digest a single meal" },
  { id: 60, answer: "Narwhal",     clues: ["🌊", "🦄", "❄️"],    difficulty: "hard",   aliases: [],                          hint: "Its 'horn' is actually a tooth that grows up to 10 feet" },
  { id: 61, answer: "Capybara",    clues: ["🇧🇷", "🌊", "🐹"],  difficulty: "hard",   aliases: [],                          hint: "World's largest rodent" },
  { id: 62, answer: "Platypus",    clues: ["🇦🇺", "🥚", "🦆"],  difficulty: "hard",   aliases: [],                          hint: "One of only five species of mammals that lay eggs" },
  { id: 63, answer: "Axolotl",     clues: ["🇲🇽", "🌊", "😊"],  difficulty: "hard",   aliases: [],                          hint: "Can regenerate entire limbs, including brain tissue" },
  { id: 64, answer: "Pangolin",    clues: ["🌍", "🛡️", "🐜"],   difficulty: "hard",   aliases: [],                          hint: "Most trafficked mammal in the world" },
  { id: 65, answer: "Armadillo",   clues: ["🛡️", "🌎", "🐾"],   difficulty: "hard",   aliases: [],                          hint: "Always gives birth to identical quadruplets" },
  { id: 66, answer: "Anteater",    clues: ["🐜", "👅", "🌿"],    difficulty: "hard",   aliases: ["ant eater"],               hint: "Has no teeth — eats up to 35,000 ants a day" },
  { id: 67, answer: "Tapir",       clues: ["🌿", "👃", "🖤"],    difficulty: "hard",   aliases: [],                          hint: "Has a flexible snout like a short elephant trunk" },
  { id: 68, answer: "Komodo Dragon", clues: ["🏝️", "🦎", "🔥"], difficulty: "hard",   aliases: ["komodo"],                  hint: "Largest living species of lizard" },
  { id: 69, answer: "Manatee",     clues: ["🌊", "🌿", "💤"],    difficulty: "hard",   aliases: ["sea cow"],                 hint: "Sometimes called the sea cow — can weigh over 1,000 lbs" },
  { id: 70, answer: "Wolverine",   clues: ["❄️", "💪", "🌲"],    difficulty: "hard",   aliases: [],                          hint: "Pound for pound one of the strongest animals alive" },
  { id: 71, answer: "Porcupine",   clues: ["🌲", "📌", "🐾"],    difficulty: "hard",   aliases: [],                          hint: "Has about 30,000 quills that can be released on contact" },
  { id: 72, answer: "Lemur",       clues: ["🏝️", "👀", "🌿"],   difficulty: "hard",   aliases: [],                          hint: "Found only in Madagascar" },
  { id: 73, answer: "Meerkat",     clues: ["🏜️", "👀", "👨‍👩‍👧"], difficulty: "hard", aliases: [],                          hint: "Takes turns standing guard while others forage" },
  { id: 74, answer: "Ibex",        clues: ["🏔️", "🐐", "🧗"],   difficulty: "hard",   aliases: ["mountain goat"],           hint: "Can climb near-vertical cliffs and dam walls" },
  { id: 75, answer: "Chinchilla",  clues: ["🌙", "🫧", "🐭"],    difficulty: "hard",   aliases: [],                          hint: "Has the densest fur of any land mammal" },
];

export default questions;
